### ISSUE TITLE
MenuItem hover effect is sometimes broken

### ISSUE THREAD

**Issue by XuanHanTan-Work** [actifyjs/actify#13]
**Describe the bug**
When moving my cursor over several menu items, the hover effect is applied to all items. On a side note, the hover effect is also slow to catch up with the cursor movement.

**To Reproduce**
Make a Menu with MenuItems.

**Expected behavior**
Only one MenuItem should have the hover effect at a time.

**Screenshots**

https://github.com/actifyjs/actify/assets/152963021/4160918d-26e8-4a6f-919f-a4cbdeebb8cc

https://github.com/actifyjs/actify/assets/152963021/6021d5a7-44ec-4018-a28d-9201bff26223

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox/Chromium/Safari
 - Version: 121

**Comment by lerte** [comment]
Try latest 0.1.74，current the docs site will not updated，I am leaving ShenZhen，back to hometown,maybe several days.

**Comment by XuanHanTan-Work** [comment]
Great, it is fixed. Enjoy your trip!

**Comment by XuanHanTan-Work** [comment]
Actually it is better but still has some issues when reloading the page.

https://github.com/actifyjs/actify/assets/152963021/2e6a2afc-7a95-432d-b700-84d1c880f9c1

**Comment by lerte** [comment]
try latest 0.1.75

**Comment by XuanHanTan-Work** [comment]
Apologies for the late reply. Yes it works, thank you. However, the hover effect animation moving across the ListItems could be faster in my opinion.

**Comment by lerte** [comment]
I add a List props transition from framer motion.
Now the Menu ListItem transition is  {{ duration: 0.1, ease: 'linear' }}

**Comment by XuanHanTan-Work** [comment]
Will check it out, thanks. If there are any issues, I will open a new issue.
