### ISSUE TITLE
Add lucide-react install instruction

### ISSUE THREAD

**Issue by 13RTK** [actifyjs/actify#18]
**Describe the bug**
In the doc of [Text Field](https://actifyjs.com/components/text-fields), the example imports the lucide-react but does not set any instruction to install it at any pre-guide.
![image](https://github.com/actifyjs/actify/assets/63441399/d0dcb001-4290-4006-a5a2-4c0951e955b8)

**Comment by lerte** [comment]
好的，我已添加提示。
B站的视频我也看了，你说text-fields没法提交是什么意思，我都有实打实的在用啊（https://lerte.com/login）
![image](https://github.com/actifyjs/actify/assets/15228321/1357c4d5-b7d4-4df9-b7d7-1e515f40f78a)

**Comment by 13RTK** [comment]
我并未提到过text-fields没法提交的问题呀，我只是说目前没有现成的表单组件库，需要自己组合text-fields和button🫣

不过您回复的速度属实出乎我的意料👍
