### ISSUE TITLE
[feat]: Add Snackbar

### ISSUE THREAD

**Issue by HironTez** [actifyjs/actify#28]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a snackbar component

**Describe the solution you'd like**
A Snackbar component that corresponds to the Material Design 3 Snackbar

**Describe alternatives you've considered**
A toast component would also be nice but i'm not sure is it matches the ideology of the project, because Material Design 3 doesn't have a toast component.

**Additional context**

**Comment by lerte** [comment]
I'll [useToast](https://react-spectrum.adobe.com/react-aria/useToast.html) in react-aria to write Snackbar component.

**Comment by lerte** [comment]
Already added [Snackbar](https://actifyjs.com/components/snackbar)

**Comment by HironTez** [comment]
Thanks! When will this be released?
