### ISSUE TITLE
Date and Time Pickers Not Opening

### ISSUE THREAD

**Issue by zohairhadi** [actifyjs/actify#34]
**Describe the bug**
Date and time picker are showing in search in the docs, but its not opening when clicking on them

**To Reproduce**
1. Go to 'https://actifyjs.com/components/'
2. Search for 'time'
3. Select time picker

**Expected behavior**
It should open date and time picker

**Screenshots**
<img width="1463" alt="Screenshot 2024-12-03 at 3 45 20 PM" src="https://github.com/user-attachments/assets/5cd6afc0-1347-4f03-8a10-56b02337a398">

**Comment by lerte** [comment]
Okay, Tks, removed from algolia

**Comment by zohairhadi** [comment]
I don't get why this was closed? has this been fixed? and is there an implementation of date and time picker available in actify?

**Comment by lerte** [comment]
![image](https://github.com/user-attachments/assets/c0e91f6e-e5bc-419f-816f-be9e1f8cd63b)
No implementations, wait for [Roadmap](https://github.com/material-components/material-web/blob/main/docs/roadmap.md)
