### ISSUE TITLE
为什么tailwindcss不在组件中配置,反而在dosc中配置?

### ISSUE THREAD

**Issue by fxwing** [actifyjs/actify#5]
为什么tailwindcss不在组件中配置,反而在dosc中配置?

**Comment by lerte** [comment]
组件没有tailwindcss配置，是因为不需要生成css文件，别人使用我这个组件的前提是react+tailwindcss。
而docs中就像一个独立的项目，是需要生成最终的css文件，当然需要tailwindcss配置啊，不然都是光秃秃的类名，而没有实质的样式。
